export const skills = [
  {
    id: "nextjs",
    label: "Next.js",
    category: "framework",
    icon: "nextjs",
    description: "App Router, SSR, SSG, ISR, Server Components",
    level: 5,
  },
  {
    id: "typescript",
    label: "TypeScript",
    category: "language",
    icon: "typescript",
    description: "Strict typing, generics, advanced types",
    level: 5,
  },
  {
    id: "react",
    label: "React",
    category: "library",
    icon: "react",
    description: "Server Components, hooks, Suspense, concurrent rendering",
    level: 5,
  },
  {
    id: "tailwind",
    label: "Tailwind CSS",
    category: "styling",
    icon: "tailwind",
    description: "Utility-first, design tokens, responsive system",
    level: 5,
  },
  {
    id: "gsap",
    label: "GSAP",
    category: "animation",
    icon: "gsap",
    description: "Timeline sequencing, ScrollTrigger, SVG morphing",
    level: 5,
  },
  {
    id: "threejs",
    label: "Three.js",
    category: "graphics",
    icon: "threejs",
    description: "WebGL, 3D rendering, shaders, immersive experiences",
    level: 4,
  },
  {
    id: "framer-motion",
    label: "Framer Motion",
    category: "animation",
    icon: "framer-motion",
    description: "Declarative animations, gestures, layout transitions",
    level: 5,
  },
  {
    id: "shadcn",
    label: "shadcn/ui",
    category: "design",
    icon: "shadcn",
    description: "Radix primitives, accessible components, design system",
    level: 5,
  },
  {
    id: "design-systems",
    label: "Design Systems",
    category: "design",
    icon: "design-systems",
    description: "Token-based architecture, scalable component libraries",
    level: 5,
  },
  {
    id: "webgl",
    label: "WebGL",
    category: "graphics",
    icon: "webgl",
    description: "Real-time 3D, particle systems, interactive visuals",
    level: 4,
  },
  {
    id: "motion-design",
    label: "Motion Design",
    category: "animation",
    icon: "motion-design",
    description: "Micro-interactions, scroll narratives, choreography",
    level: 5,
  },
  {
    id: "seo",
    label: "SEO Architecture",
    category: "performance",
    icon: "seo",
    description: "Structured data, Core Web Vitals, semantic HTML",
    level: 5,
  },
  {
    id: "performance",
    label: "Performance",
    category: "performance",
    icon: "performance",
    description: "Lighthouse 100, bundle optimization, lazy loading",
    level: 5,
  },
  {
    id: "responsive",
    label: "Responsive Design",
    category: "design",
    icon: "responsive",
    description: "Mobile-first, adaptive layouts, cross-device",
    level: 5,
  },
  {
    id: "ux-architecture",
    label: "UX Architecture",
    category: "design",
    icon: "ux-architecture",
    description: "User flows, information architecture, accessibility",
    level: 4,
  },
] as const;

export type Skill = (typeof skills)[number];
export type SkillCategory = Skill["category"];
